arm64:build:
  variables:
    ARCH: arm64

  stage: build

  script:
  - if [ -f init ]; then chmod 500 init; fi
  - echo -n ${CI_COMMIT_SHORT_SHA} > VERSION
  - rm -rf node_modules database/seeds database/schema database/factories/*
  - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}:${VERSIONARCH} .
  - docker push ${CI_REGISTRY_IMAGE}:${VERSIONARCH}

  tags:
  - docker
  - arm64
  only:
  - master
